WITH deduplicate AS (
         SELECT max(raw__weatherapp_1.modified_timestamp) AS modified_timestamp,
            raw__weatherapp_1.id
           FROM raw__weatherapp raw__weatherapp_1
          GROUP BY raw__weatherapp_1.id
        )
 SELECT raw__weatherapp.ingestion_timestamp,
    raw__weatherapp.modified_timestamp,
    raw__weatherapp.id,
    ((raw__weatherapp.data)::json -> 'time_epoch'::text) AS time_epoch,
    ((raw__weatherapp.data)::json -> 'time'::text) AS "time",
    ((raw__weatherapp.data)::json -> 'temp_c'::text) AS temp_c,
    ((raw__weatherapp.data)::json -> 'temp_f'::text) AS temp_f,
    ((raw__weatherapp.data)::json -> 'is_day'::text) AS is_day,
    (((raw__weatherapp.data)::json -> 'condition'::text) ->> 'text'::text) AS condition_text,
    (((raw__weatherapp.data)::json -> 'condition'::text) ->> 'icon'::text) AS condition_icon,
    (((raw__weatherapp.data)::json -> 'condition'::text) ->> 'code'::text) AS condition_code,
    ((raw__weatherapp.data)::json -> 'wind_mph'::text) AS wind_mph,
    ((raw__weatherapp.data)::json -> 'wind_kph'::text) AS wind_kph,
    ((raw__weatherapp.data)::json -> 'wind_degree'::text) AS wind_degree,
    ((raw__weatherapp.data)::json -> 'wind_dir'::text) AS wind_dir,
    ((raw__weatherapp.data)::json -> 'pressure_mb'::text) AS pressure_mb,
    ((raw__weatherapp.data)::json -> 'pressure_in'::text) AS pressure_in,
    ((raw__weatherapp.data)::json -> 'precip_mm'::text) AS precip_mm,
    ((raw__weatherapp.data)::json -> 'precip_in'::text) AS precip_in,
    ((raw__weatherapp.data)::json -> 'snow_cm'::text) AS snow_cm,
    ((raw__weatherapp.data)::json -> 'humidity'::text) AS humidity,
    ((raw__weatherapp.data)::json -> 'cloud'::text) AS cloud,
    ((raw__weatherapp.data)::json -> 'feelslike_c'::text) AS feelslike_c,
    ((raw__weatherapp.data)::json -> 'feelslike_f'::text) AS feelslike_f,
    ((raw__weatherapp.data)::json -> 'windchill_c'::text) AS windchill_c,
    ((raw__weatherapp.data)::json -> 'windchill_f'::text) AS windchill_f,
    ((raw__weatherapp.data)::json -> 'heatindex_c'::text) AS heatindex_c,
    ((raw__weatherapp.data)::json -> 'heatindex_f'::text) AS heatindex_f,
    ((raw__weatherapp.data)::json -> 'dewpoint_c'::text) AS dewpoint_c,
    ((raw__weatherapp.data)::json -> 'dewpoint_f'::text) AS dewpoint_f,
    ((raw__weatherapp.data)::json -> 'will_it_rain'::text) AS will_it_rain,
    ((raw__weatherapp.data)::json -> 'chance_of_rain'::text) AS chance_of_rain,
    ((raw__weatherapp.data)::json -> 'will_it_snow'::text) AS will_it_snow,
    ((raw__weatherapp.data)::json -> 'chance_of_snow'::text) AS chance_of_snow,
    ((raw__weatherapp.data)::json -> 'vis_km'::text) AS vis_km,
    ((raw__weatherapp.data)::json -> 'vis_miles'::text) AS vis_miles,
    ((raw__weatherapp.data)::json -> 'gust_mph'::text) AS gust_mph,
    ((raw__weatherapp.data)::json -> 'gust_kph'::text) AS gust_kph,
    ((raw__weatherapp.data)::json -> 'uv'::text) AS uv
   FROM (raw__weatherapp
     RIGHT JOIN deduplicate deduplicate ON (((raw__weatherapp.id = deduplicate.id) AND (raw__weatherapp.modified_timestamp = deduplicate.modified_timestamp))));d